language: java
sudo: required
before_script:
  - sudo sysctl -w vm.max_map_count=262144

install: true

jdk:
  - oraclejdk8

script: mvn clean verify -Ddocker.showLogs -B

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
